import { useState } from "react";
import { useAuth } from "../AuthContext";
import { Link, useLocation, useNavigate } from "../router";
import { careerDate, careerRequest, moveItem, useCareerResource, useUnsavedChanges, type Answers, type CareerForm, type CareerPageResult, type CareerQuestion, type FormDraft, type QuestionType } from "../careers";
import CareerFields, { CareerPagination, CareerResourceState } from "../Components/CareerFields";
import { ApplicationList } from "./Applications";
import "./Careers.css";

const types: Record<QuestionType, string> = { short: "Short answer", paragraph: "Long answer", choice: "Multiple choice", checkboxes: "Checkboxes", ranking: "Ranking", scale: "Linear scale" };
const newQuestion = (type: QuestionType = "paragraph"): CareerQuestion => ({ id: crypto.randomUUID(), label: "", help: "", type, required: true, ...(["choice", "checkboxes", "ranking"].includes(type) ? { options: ["Option 1", "Option 2"] } : {}), ...(type === "scale" ? { min: 1, max: 5, minLabel: "", maxLabel: "" } : {}) });
function template(kind: string): FormDraft {
  const question = (label: string, type: QuestionType = "paragraph", extra: Partial<CareerQuestion> = {}) => ({ ...newQuestion(type), label, ...extra });
  return { title: `${kind} application`, category: kind === "Tester" ? "Quality assurance" : kind === "Moderator" ? "Community" : "Development", description: `Help shape Tower Eclipse as a ${kind.toLowerCase()}. Tell us about your experience and how you would contribute to the team.`, commitment: "", closesAt: null, confirmation: "Thanks for applying! Follow your application on your profile for review updates.", questions: [question("Why would you like to join the team?"), question("What relevant experience would you bring?"), question("What is your time zone?", "short"), question("How many hours could you usually contribute each week?", "choice", { options: ["Less than 3 hours", "3–5 hours", "6–10 hours", "More than 10 hours"] }), question(kind === "Tester" ? "Describe how you would document a bug so a developer can reproduce it." : kind === "Moderator" ? "How would you handle a disagreement between two community members?" : "Share examples of your work and explain your contribution."), question("Is there anything else you would like us to know?", "paragraph", { required: false })] };
}

function FormEditor({ initial }: { initial: CareerForm }) {
  const { auth } = useAuth();
  const [saved, setSaved] = useState(initial);
  const [draft, setDraft] = useState<FormDraft>(initial.draft);
  const [preview, setPreview] = useState(false);
  const [previewAnswers, setPreviewAnswers] = useState<Answers>({});
  const [working, setWorking] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [confirmation, setConfirmation] = useState<"publish" | "close" | null>(null);
  const dirty = JSON.stringify(draft) !== JSON.stringify(saved.draft);
  useUnsavedChanges(dirty);
  const change = <K extends keyof FormDraft>(key: K, value: FormDraft[K]) => { setDraft(old => ({ ...old, [key]: value })); setNotice(""); setConfirmation(null); };
  const changeQuestion = (index: number, value: CareerQuestion) => change("questions", draft.questions.map((q, i) => i === index ? value : q));
  async function save(action: "save" | "publish" | "close") {
    if (!auth || working) return;
    setWorking(true); setError(""); setNotice("");
    try { const next = await careerRequest<CareerForm>(`/admin/forms/${saved.id}`, { method: "PUT", csrf: auth.csrfToken, body: { action, revision: saved.revision, draft } }); setSaved(next); if (action !== "close") setDraft(next.draft); setConfirmation(null); setNotice(action === "publish" ? "Published. This version is now accepting applications on Careers." : action === "close" ? "Opening closed. Existing applications remain available for review." : "Draft saved. Your published form stays as it was until you publish again."); }
    catch (reason) { setError((reason as Error).message); }
    finally { setWorking(false); }
  }
  return <>
    <header className="career-detail-header"><div><span className="career-eyebrow">APPLICATION BUILDER / {saved.state.toUpperCase()}</span><h2>{draft.title || "Untitled opening"}</h2><p>{dirty ? "Unsaved changes" : `Saved ${careerDate(saved.updatedAt)}`} · {draft.questions.length}/40 questions</p></div><Link className="career-button" to={`/admin/careers/review?formId=${saved.id}`}>Review applications ↗</Link></header>
    <div className="career-editor-bar"><div className="career-switch" role="group" aria-label="Builder view"><button aria-pressed={!preview} onClick={() => setPreview(false)}>Edit form</button><button aria-pressed={preview} onClick={() => { setPreviewAnswers({}); setPreview(true); }}>Preview</button></div><div className="career-actions"><button className="career-button" disabled={working || !dirty} onClick={() => void save("save")}>{working ? "Saving…" : "Save draft"}</button>{saved.state === "open" && <button className="career-button" disabled={working} onClick={() => setConfirmation("close")}>Close opening</button>}<button className="career-button is-primary" disabled={working} onClick={() => setConfirmation("publish")}>{saved.publishedVersion ? "Publish version ↗" : "Publish opening ↗"}</button></div></div>
    {error && <div className="career-notice is-error" role="alert">{error}</div>}{notice && <div className="career-notice" role="status">{notice}</div>}
    {confirmation && <div className="career-notice"><h3>{confirmation === "publish" ? "Publish this form?" : "Close this opening?"}</h3><p>{confirmation === "publish" ? "Your current questions and description will be published on Careers. Existing applications keep the form version they answered." : "New applications will stop immediately. You can continue reviewing existing submissions. Unsaved edits stay in the builder."}</p><div className="career-actions"><button className="career-button is-primary" disabled={working} onClick={() => void save(confirmation)}>{working ? "Saving…" : `Confirm ${confirmation}`}</button><button className="career-button" disabled={working} onClick={() => setConfirmation(null)}>Cancel</button></div></div>}
    {preview ? <section className="career-preview"><div className="career-notice">Preview only — answers entered here are not submitted or saved.</div><div className="career-card"><span className="career-category">{draft.category}</span><h3>{draft.title}</h3><p className="career-answer">{draft.description}</p><p>{draft.commitment}</p><p className="career-help">Closes: {careerDate(draft.closesAt)}</p></div><CareerFields questions={draft.questions} answers={previewAnswers} onChange={setPreviewAnswers} /></section> : <fieldset className="career-editor-fieldset" disabled={working}><div className="career-builder-layout"><main>
      <section className="career-card career-editor-settings"><span className="career-eyebrow">OPENING DETAILS</span><h3>Make a good first impression.</h3><label>Opening title<input maxLength={100} value={draft.title} onChange={e => change("title", e.target.value)} /></label><div className="career-input-grid"><label>Category<input maxLength={60} value={draft.category} onChange={e => change("category", e.target.value)} placeholder="Quality assurance, Community, Development…" /></label><label>Commitment / role details<input maxLength={150} value={draft.commitment} onChange={e => change("commitment", e.target.value)} placeholder="e.g. Volunteer · 3–5 hours/week" /></label></div><label>Description<textarea rows={5} maxLength={4000} value={draft.description} onChange={e => change("description", e.target.value)} placeholder="Explain the role, requirements, and what applicants can expect." /></label><label>Closing date and time (your local time)<input type="datetime-local" value={draft.closesAt ? new Date(Date.parse(draft.closesAt) - new Date(draft.closesAt).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ""} onChange={e => change("closesAt", e.target.value ? new Date(e.target.value).toISOString() : null)} /></label><p className="career-help">Leave blank to keep the opening available until you close it. Applicants see dates in their own time zone.</p><label>Message after submission<textarea rows={3} maxLength={1000} value={draft.confirmation} onChange={e => change("confirmation", e.target.value)} /></label></section>
      {draft.questions.map((q, index) => <section className="career-card career-question-editor" key={q.id}><div className="career-question-editor-heading"><span className="career-eyebrow">QUESTION {String(index + 1).padStart(2, "0")}</span><div className="career-actions"><button type="button" className="career-mini-button" disabled={index === 0} aria-label={`Move question ${index + 1} up`} onClick={() => change("questions", moveItem(draft.questions, index, -1))}>↑</button><button type="button" className="career-mini-button" disabled={index === draft.questions.length - 1} aria-label={`Move question ${index + 1} down`} onClick={() => change("questions", moveItem(draft.questions, index, 1))}>↓</button><button type="button" className="career-mini-button" disabled={draft.questions.length >= 40} onClick={() => change("questions", [...draft.questions.slice(0, index + 1), { ...q, id: crypto.randomUUID() }, ...draft.questions.slice(index + 1)])}>Duplicate</button><button type="button" className="career-mini-button" onClick={() => { if (window.confirm(`Remove question ${index + 1}?`)) change("questions", draft.questions.filter((_, i) => i !== index)); }}>Remove</button></div></div><label>Question<input maxLength={300} value={q.label} onChange={e => changeQuestion(index, { ...q, label: e.target.value })} placeholder="What would you like to ask?" /></label><div className="career-input-grid"><label>Answer type<select value={q.type} onChange={e => changeQuestion(index, { ...newQuestion(e.target.value as QuestionType), id: q.id, label: q.label, help: q.help, required: q.required })}>{Object.entries(types).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Help text (optional)<input maxLength={800} value={q.help} onChange={e => changeQuestion(index, { ...q, help: e.target.value })} /></label></div>
        {q.options && <div className="career-edit-options"><p className="career-help">Options · {q.type === "ranking" ? "Applicants rank all options." : q.type === "checkboxes" ? "Applicants can choose several." : "Applicants choose one."}</p>{q.options.map((option, optionIndex) => <div key={optionIndex}><span>{optionIndex + 1}</span><input aria-label={`Question ${index + 1}, option ${optionIndex + 1}`} maxLength={150} value={option} onChange={e => changeQuestion(index, { ...q, options: q.options!.map((v, i) => i === optionIndex ? e.target.value : v) })} /><button type="button" className="career-mini-button" disabled={q.options!.length <= 2} aria-label={`Remove option ${optionIndex + 1}`} onClick={() => changeQuestion(index, { ...q, options: q.options!.filter((_, i) => i !== optionIndex) })}>×</button></div>)}<button type="button" className="career-link" disabled={q.options.length >= 15} onClick={() => changeQuestion(index, { ...q, options: [...q.options!, `Option ${q.options!.length + 1}`] })}>+ Add option</button></div>}
        {q.type === "scale" && <div className="career-input-grid"><label>Starts at<select value={q.min} onChange={e => changeQuestion(index, { ...q, min: Number(e.target.value) })}><option value={0}>0</option><option value={1}>1</option></select></label><label>Ends at<select value={q.max} onChange={e => changeQuestion(index, { ...q, max: Number(e.target.value) })}>{Array.from({ length: 9 }, (_, i) => i + 2).map(n => <option key={n} value={n}>{n}</option>)}</select></label><label>Low label<input maxLength={80} value={q.minLabel} onChange={e => changeQuestion(index, { ...q, minLabel: e.target.value })} placeholder="e.g. Not confident" /></label><label>High label<input maxLength={80} value={q.maxLabel} onChange={e => changeQuestion(index, { ...q, maxLabel: e.target.value })} placeholder="e.g. Very confident" /></label></div>}
        <label className="career-check"><input type="checkbox" checked={q.required} onChange={e => changeQuestion(index, { ...q, required: e.target.checked })} />Required question</label>
      </section>)}
      <button type="button" className="career-add-question" disabled={draft.questions.length >= 40} onClick={() => change("questions", [...draft.questions, newQuestion()])}>+ Add a question</button>
    </main><aside className="career-card career-builder-aside"><span className="career-eyebrow">YOUR FORM, YOUR WAY</span><h3>Start with a question.</h3><p>Mix answer types to learn how someone thinks, what they know, and where they want to help.</p><div className="career-type-buttons">{Object.entries(types).map(([type, label]) => <button type="button" className="career-button" key={type} disabled={draft.questions.length >= 40} onClick={() => change("questions", [...draft.questions, newQuestion(type as QuestionType)])}>+ {label}</button>)}</div>{!draft.questions.length && <><hr /><h4>Or start from a template</h4>{["Tester", "Moderator", "Developer"].map(kind => <button type="button" key={kind} className="career-button" onClick={() => { setDraft(template(kind)); setNotice(""); }}>{kind} application</button>)}<p className="career-help">Templates are editable starting points. Review the questions and role details before publishing.</p></>}<hr /><p className="career-help">Keep applications focused. Avoid collecting dates of birth, addresses, passwords, or other sensitive information.</p><p className="career-help">Drafts save when you click Save draft. Publishing creates a preserved form version for future submissions.</p></aside></div></fieldset>}
  </>;
}

export default function AdminCareers({ formId, review = false }: { formId?: string; review?: boolean }) {
  const { auth } = useAuth();
  const navigate = useNavigate();
  const { search } = useLocation();
  const [pages, setPages] = useState<(string | null)[]>([null]);
  const [error, setError] = useState("");
  const [working, setWorking] = useState(false);
  const forms = useCareerResource<CareerPageResult<CareerForm>>(!formId && !review ? `/admin/forms?${new URLSearchParams(pages.at(-1) ? { cursor: pages.at(-1)! } : {})}` : null);
  const form = useCareerResource<CareerForm>(formId ? `/admin/forms/${encodeURIComponent(formId)}` : null);
  const selectedForm = new URLSearchParams(search).get("formId") ?? "";
  return <section className="content-band careers-page"><Link className="career-back" to={formId || review ? "/admin/careers" : "/admin"}>← {formId || review ? "Manage openings" : "Admin"}</Link>{formId ? <><CareerResourceState {...form} />{form.data && <FormEditor key={formId} initial={form.data} />}</> : <><header className="career-detail-header"><div><span className="career-eyebrow">TEAM MANAGEMENT</span><h2>{review ? "Application review" : "Open the next door."}</h2><p>{review ? "Read applications, compare experience, and keep people informed." : "Create an opening. Find your people. Build the next chapter of Tower Eclipse."}</p></div><div className="career-actions"><Link className="career-button" to="/careers">View Careers ↗</Link>{!review && <><Link className="career-button" to="/admin/careers/review">Review applications</Link><button className="career-button is-primary" disabled={working} onClick={async () => { if (!auth) return; setWorking(true); setError(""); try { const created = await careerRequest<CareerForm>("/admin/forms", { method: "POST", csrf: auth.csrfToken, body: {} }); navigate(`/admin/careers/forms/${created.id}`); } catch (reason) { setError((reason as Error).message); setWorking(false); } }}>{working ? "Creating…" : "+ New opening"}</button></>}</div></header>{error && <p className="career-notice is-error" role="alert">{error}</p>}{review ? <section className="career-card">{selectedForm && <p className="career-notice">Showing applications for one opening. <Link to="/admin/careers/review">Show all openings</Link></p>}<ApplicationList key={selectedForm} admin formId={selectedForm} /></section> : <><CareerResourceState {...forms} />{forms.data && (forms.data.items.length ? <div className="career-grid">{forms.data.items.map(item => <article className="career-card career-opening" key={item.id}><div className="career-opening-top"><span className="career-category">{item.category}</span><span className="career-status">{item.state === "open" && item.closesAt && Date.parse(item.closesAt) <= Date.now() ? "Deadline passed" : item.state}</span></div><h3>{item.title}</h3><p>{item.description || "Add a description and questions to get this opening ready."}</p><small>Updated {careerDate(item.updatedAt)}</small><div className="career-actions"><Link className="career-button is-primary" to={`/admin/careers/forms/${item.id}`}>Edit form →</Link><Link className="career-button" to={`/admin/careers/review?formId=${item.id}`}>Applications</Link></div></article>)}</div> : <div className="career-card career-empty"><h3>Your first opening starts here.</h3><p>Create a new opening, use a Tester, Moderator, or Developer template, and make it your own.</p></div>)}{forms.data && <CareerPagination pages={pages} setPages={setPages} nextCursor={forms.data.nextCursor} loading={forms.loading} />}</>}</>}</section>;
}
