import { useState } from "react";
import { useAuth } from "../AuthContext";
import { Link, useNavigate } from "../router";
import { careerDate, careerRequest, useCareerResource, useUnsavedChanges, type Answers, type ApplicantIdentity, type CareerForm, type CareerPageResult } from "../careers";
import CareerFields, { CareerPagination, CareerResourceState } from "../Components/CareerFields";
import "./Careers.css";

function ApplicationForm({ data }: { data: { form: CareerForm; identity: ApplicantIdentity; existingApplicationId: string | null } }) {
  const { auth } = useAuth();
  const navigate = useNavigate();
  const [answers, setAnswers] = useState<Answers>({});
  const [consent, setConsent] = useState(false);
  const [working, setWorking] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");
  useUnsavedChanges(!submitted && Object.keys(answers).length > 0);
  const { form, identity } = data;
  const answered = form.questions.filter(q => { const v = answers[q.id]; return v !== undefined && v !== "" && (!Array.isArray(v) || v.length > 0); }).length;
  if (data.existingApplicationId) return <div className="career-card career-empty"><span className="career-eyebrow">APPLICATION RECEIVED</span><h3>You’ve already applied for this opening.</h3><p>Check your status, read updates, or withdraw your application from your profile.</p><Link className="career-button is-primary" to={`/applications/${data.existingApplicationId}`}>View my application →</Link></div>;
  return <form className="career-form-layout" onSubmit={async e => {
    e.preventDefault(); if (working || !auth) return;
    setWorking(true); setError("");
    try { const result = await careerRequest<{ id: string }>(`/forms/${form.id}/applications`, { method: "POST", csrf: auth.csrfToken, body: { versionId: form.versionId, answers, consent } }); setSubmitted(true); navigate(`/applications/${result.id}?submitted=1`); }
    catch (reason) { setError((reason as Error).message); setWorking(false); }
  }}>
    <div><CareerFields questions={form.questions} answers={answers} onChange={setAnswers} disabled={working} />
      <div className="career-card career-submit"><h3>Ready to send?</h3><p>Review your answers before submitting. You can submit once for this opening; answers cannot be edited afterward.</p><p>Your answers and the identities shown here will be visible to the team’s admins and developers reviewing applications. Do not include passwords, your home address, or sensitive personal information.</p><label className="career-check"><input type="checkbox" required checked={consent} disabled={working} onChange={e => setConsent(e.target.checked)} /><span>I have read the <Link to="/privacy" target="_blank">Privacy Policy</Link> and <Link to="/terms" target="_blank">Terms of Service</Link>, and understand how my application will be reviewed.</span></label>{error && <p className="career-notice is-error" role="alert">{error}</p>}<button className="career-button is-primary" disabled={working} type="submit">{working ? "Submitting…" : "Submit application ↗"}</button><p className="career-help">Your answers stay on this page until submitted. They are not saved if you leave.</p></div>
    </div>
    <aside className="career-card career-form-aside"><span className="career-eyebrow">YOUR APPLICATION</span><h3>A place on the team starts here.</h3><div className="career-progress" role="progressbar" aria-label="Questions answered" aria-valuemin={0} aria-valuemax={form.questions.length} aria-valuenow={answered}><span style={{ width: `${100 * answered / Math.max(1, form.questions.length)}%` }} /></div><p>{answered} of {form.questions.length} answered</p><div className="career-identity"><img src="/social/discord.png" alt="Discord" /><div><strong>@{identity.username}</strong><small>{identity.discordId}</small></div></div><div className="career-identity"><img src="/social/roblox.png" alt="Roblox" /><div><strong>@{identity.roblox.username}</strong><small>{identity.roblox.userId}</small></div></div><p className="career-help">These verified accounts will be attached when you submit.</p><hr /><span className="career-eyebrow">CLOSES</span><p>{careerDate(form.closesAt)}</p><p className="career-help">After submitting, follow review decisions and feedback on Account → Applications.</p></aside>
  </form>;
}

export default function Careers({ formId }: { formId?: string }) {
  const { auth, loading: authLoading } = useAuth();
  const [pages, setPages] = useState<(string | null)[]>([null]);
  const resource = useCareerResource<CareerPageResult<CareerForm>>(!formId ? `/forms?${new URLSearchParams({ ...(pages.at(-1) ? { cursor: pages.at(-1)! } : {}) })}` : null);
  const form = useCareerResource<{ form: CareerForm; identity: ApplicantIdentity; existingApplicationId: string | null }>(formId && auth ? `/forms/${encodeURIComponent(formId)}` : null);
  return <section className="content-band careers-page">
    {formId && <Link className="career-back" to="/careers">← All openings</Link>}
    <header className="career-hero"><div><span className="career-eyebrow">{formId ? "JOIN THE TEAM" : "CAREERS & COMMUNITY"}</span><h2>{formId ? form.data?.form.title ?? "Your next chapter." : <>Build what<br /><em>comes next.</em></>}</h2><p className="career-intro">{formId ? form.data?.form.description ?? "Sign in and connect your accounts to begin your application." : "Help shape Tower Eclipse. Bring your ideas, your curiosity, and your care for the community."}</p>{form.data && <div className="career-meta"><span>{form.data.form.category}</span><span>{form.data.form.questions.length} questions</span>{form.data.form.commitment && <span>{form.data.form.commitment}</span>}</div>}</div><div className="career-hero-aside">{!formId && <><span className="career-orbit" aria-hidden="true">↗</span><p>Different strengths.<br />One shared world.</p></>}<div className="career-actions">{auth && <Link className="career-button" to="/login?tab=applications">My applications</Link>}{auth?.user.role === "dev" && <Link className="career-button" to="/admin/careers">Manage openings ↗</Link>}</div></div></header>
    {!formId ? <><div className="career-section-heading"><div><span className="career-eyebrow">FIND YOUR PLACE</span><h3>Open opportunities</h3></div><span className="career-muted">Discord + Roblox required to apply</span></div><CareerResourceState {...resource} />{resource.data && (resource.data.items.length ? <div className="career-grid">{resource.data.items.map((opening, index) => <article className="career-card career-opening" key={opening.id}><div className="career-opening-top"><span className="career-category">{opening.category}</span><span className="career-open">● Open</span></div><span className="career-opening-number" aria-hidden="true">{String((pages.length - 1) * 20 + index + 1).padStart(2, "0")}</span><h3>{opening.title}</h3><p>{opening.description}</p><div className="career-opening-bottom"><div>{opening.commitment && <strong>{opening.commitment}</strong>}<small>{opening.closesAt ? `Closes ${careerDate(opening.closesAt)}` : "Applications open until filled"}</small></div><Link className="career-button is-primary" to={`/careers/${opening.id}`}>View & apply ↗</Link></div></article>)}</div> : <div className="career-card career-empty"><span className="career-eyebrow">GOOD THINGS TAKE A TEAM</span><h3>No openings right now.</h3><p>Check back for new ways to join the team. You can still follow development and get involved in our community.</p><Link className="career-button" to="/news">Explore the latest news ↗</Link></div>)}{resource.data && <CareerPagination pages={pages} setPages={setPages} nextCursor={resource.data.nextCursor} loading={resource.loading} />}<div className="career-steps">{[["01", "Connect", "Sign in with Discord and link your Roblox account on your profile."], ["02", "Apply", "Choose an opening and tell us what you would bring to the team."], ["03", "Stay updated", "Track your application and read feedback from the team on your profile."]].map(([number, title, detail]) => <div key={number}><span>{number}</span><h4>{title}</h4><p>{detail}</p></div>)}</div></> : authLoading ? <p role="status">Checking your account…</p> : !auth ? <div className="career-card career-empty"><h3>Let’s connect your accounts.</h3><p>Sign in with Discord, then link your Roblox account in Account → Connections. Return to this opening when you’re ready.</p><Link className="career-button is-primary" to="/login">Sign in with Discord ↗</Link></div> : <><CareerResourceState {...form} />{form.error && <Link className="career-button" to="/login?tab=connections">Manage account connections →</Link>}{form.data && <ApplicationForm key={form.data.form.versionId} data={form.data} />}</>}
  </section>;
}
