import { useEffect, useState } from 'react';
import { apiJson } from '../api';
import { useAuth } from '../AuthContext';
type Content = { version: string; intro: string; steps: { id: string; title: string; paragraphs: string[]; bullets?: string[]; links?: [string, string][] }[]; archives: [string, string][]; completed: Record<string, string> };
export default function TesterOnboarding() {
  const { auth } = useAuth(); const [data, setData] = useState<Content | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [revision, setRevision] = useState(0);
  useEffect(() => { const controller = new AbortController(); apiJson<Content>('/api/account/onboarding', 'GET', undefined, undefined, controller.signal).then(value => setData(value)).catch(reason => { if (!controller.signal.aborted) setError(reason.message); }); return () => controller.abort(); }, [revision]);
  async function mark(stepId: string, complete: boolean) { if (!data) return; setBusy(true); setError(''); try { const result = await apiJson<{ completed: Record<string, string> }>('/api/account/onboarding', 'PUT', { stepId, complete, version: data.version }, auth!.csrfToken); setData(current => current ? { ...current, completed: result.completed } : current); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Progress could not be saved.'); } finally { setBusy(false); } }
  return <section className="account-card onboarding"><p className="section-kicker">TESTER RESOURCES</p><h3>Your testing handbook</h3>{error && <div role="alert"><p>{error}</p><button className="secondary-button" onClick={() => { setError(''); setRevision(value => value + 1); }}>RETRY</button></div>}{!data && !error && <p role="status">Loading resources…</p>}{data && <><p>{data.intro}</p><label className="onboarding-progress">{Object.keys(data.completed).length} of {data.steps.length} steps reviewed<progress max={data.steps.length} value={Object.keys(data.completed).length} /></label><p>Your progress is saved to your account and visible to admins. This checklist is self-reported, not a qualification or performance score.</p>{data.steps.map((step, index) => <details key={step.id} className="onboarding-step" open={index === 0 && !data.completed[step.id] ? true : undefined}><summary>{data.completed[step.id] ? '✓' : index + 1} · {step.title}</summary>{step.paragraphs.map(text => <p key={text}>{text}</p>)}{step.bullets && <ul>{step.bullets.map(text => <li key={text}>{text}</li>)}</ul>}{step.links && <ul>{step.links.map(([label, href]) => <li key={href}><a href={href} target="_blank" rel="noopener noreferrer">{label} ↗</a></li>)}</ul>}<label className="onboarding-check"><input type="checkbox" disabled={busy} checked={!!data.completed[step.id]} onChange={event => void mark(step.id, event.target.checked)} />I have reviewed this step.</label></details>)}<details className="onboarding-step"><summary>Historical game versions</summary><p>For historical comparisons only. Access and availability may change; use the current game for routine testing unless a lead asks otherwise.</p><ul>{data.archives.map(([label, id]) => <li key={id}><a href={`https://www.roblox.com/games/${id}`} target="_blank" rel="noopener noreferrer">{label} ↗</a></li>)}</ul></details><p className="account-footnote">Guide version {data.version}. Ask a QA Lead if the current game differs from these instructions.</p></>}</section>;
}
